import type { ConsoleData } from "../types";

type ConsoleProjectData = Omit<ConsoleData, "projects">;

const projects = {
  currentProjectId: "project-1",
  projects: [
    {
      id: "project-1",
      name: "Acme Returns Portal",
      repository: "git@github.com:acme/returns-portal.git",
      projectDirectory: "workspace/acme-returns-portal",
      defaultBranch: "main",
      health: "ready",
      lastActivityAt: "2026-04-29T03:45:00.000Z",
    },
    {
      id: "project-2",
      name: "Northwind Supply Planner",
      repository: "git@github.com:northwind/supply-planner.git",
      projectDirectory: "workspace/northwind-supply-planner",
      defaultBranch: "develop",
      health: "ready",
      lastActivityAt: "2026-04-29T02:20:00.000Z",
    },
  ],
} satisfies ConsoleData["projects"];

const cliAdapterConfig = {
  id: "codex-cli",
  displayName: "Codex CLI",
  schemaVersion: 5,
  executable: "codex",
  argumentTemplate: ["-a", "{{approval}}", "-c", "model_reasoning_effort=\"{{reasoning_effort}}\"", "-c", "service_tier=\"{{service_tier}}\"", "-c", "features.fast_mode={{fast_mode}}", "exec", "--json", "--sandbox", "{{sandbox}}", "--model", "{{model}}", "--output-schema", "{{output_schema}}", "{{prompt}}"],
  resumeArgumentTemplate: ["-a", "{{approval}}", "--sandbox", "{{sandbox}}", "-c", "model_reasoning_effort=\"{{reasoning_effort}}\"", "-c", "service_tier=\"{{service_tier}}\"", "-c", "features.fast_mode={{fast_mode}}", "{{profile_flag}}", "{{profile}}", "exec", "resume", "--json", "-m", "{{model}}", "{{resume_session_id}}", "{{resume_prompt}}"],
  configSchema: { type: "object" },
  formSchema: { fields: ["executable", "defaults.model", "defaults.reasoningEffort", "defaults.serviceTier", "defaults.fastMode", "defaults.sandbox", "defaults.approval"] },
  defaults: { model: "gpt-5.5", reasoningEffort: "high", serviceTier: "fast", fastMode: true, sandbox: "workspace-write", approval: "never" },
  environmentAllowlist: [],
  outputMapping: { sessionIdJsonPath: "session_id" },
  status: "active",
  updatedAt: "2026-04-29T03:45:00.000Z",
} satisfies ConsoleData["settings"]["cliAdapter"]["active"];

const settings = {
  cliAdapter: {
    active: cliAdapterConfig,
    presets: [
      cliAdapterConfig,
      {
        id: "gemini-cli",
        displayName: "Google Gemini CLI",
        schemaVersion: 1,
        executable: "gemini",
        argumentTemplate: ["--model", "{{model}}", "--output-format", "stream-json", "-p", "{{prompt}}"],
        resumeArgumentTemplate: ["--model", "{{model}}", "--output-format", "stream-json", "--resume", "{{resume_session_id}}", "-p", "{{resume_prompt}}"],
        configSchema: { type: "object" },
        formSchema: cliAdapterConfig.formSchema,
        defaults: {
          model: "gemini-3-pro-preview",
          reasoningEffort: "medium",
          sandbox: "danger-full-access",
          approval: "never",
          costRates: {
            "gemini-3-pro-preview": {
              inputUsdPer1M: 2,
              cachedInputUsdPer1M: 0.2,
              outputUsdPer1M: 12,
              reasoningOutputUsdPer1M: 12,
            },
          },
        },
        environmentAllowlist: ["GEMINI_API_KEY", "GOOGLE_API_KEY", "GOOGLE_CLOUD_PROJECT", "GOOGLE_GENAI_USE_VERTEXAI"],
        outputMapping: { eventStream: "json", outputSchema: "skill-output.schema.json", sessionIdPath: "session_id", responseTextPaths: ["response", "result.response", "message.content", "content", "text"] },
        status: "draft",
        updatedAt: "1970-01-01T00:00:00.000Z",
      },
      {
        id: "claude-cli",
        displayName: "Claude Code CLI",
        schemaVersion: 3,
        executable: "claude",
        argumentTemplate: ["-p", "{{prompt}}", "--model", "{{model}}", "--effort", "{{reasoning_effort}}", "--output-format", "json", "--json-schema", "{{output_schema_json}}", "--permission-mode", "{{claude_permission_mode}}", "--allowedTools", "{{claude_allowed_tools}}"],
        resumeArgumentTemplate: ["-p", "{{resume_prompt}}", "--resume", "{{resume_session_id}}", "--model", "{{model}}", "--effort", "{{reasoning_effort}}", "--output-format", "json", "--json-schema", "{{output_schema_json}}", "--permission-mode", "{{claude_permission_mode}}", "--allowedTools", "{{claude_allowed_tools}}"],
        configSchema: { type: "object" },
        formSchema: cliAdapterConfig.formSchema,
        defaults: {
          model: "sonnet",
          reasoningEffort: "medium",
          sandbox: "danger-full-access",
          approval: "never",
          costRates: {},
        },
        environmentAllowlist: [
          "ANTHROPIC_API_KEY",
          "ANTHROPIC_AUTH_TOKEN",
          "ANTHROPIC_BASE_URL",
          "ANTHROPIC_MODEL",
          "ANTHROPIC_SMALL_FAST_MODEL",
          "ANTHROPIC_DEFAULT_OPUS_MODEL",
          "ANTHROPIC_DEFAULT_SONNET_MODEL",
          "ANTHROPIC_DEFAULT_HAIKU_MODEL",
          "CLAUDE_CODE_OAUTH_TOKEN",
        ],
        outputMapping: { eventStream: "json", outputSchema: "skill-output.schema.json", sessionIdPath: "session_id", responseTextPaths: ["structured_output", "result", "message.content", "content", "text"] },
        status: "draft",
        updatedAt: "1970-01-01T00:00:00.000Z",
      },
    ],
    validation: { valid: true, errors: [], warnings: [], command: "codex", args: cliAdapterConfig.argumentTemplate },
    lastDryRun: { status: "passed", errors: [], command: "codex", args: cliAdapterConfig.argumentTemplate, at: "2026-04-29T03:45:00.000Z" },
  },
  commands: [
    { action: "validate_cli_adapter_config", entityType: "cli_adapter" },
    { action: "save_cli_adapter_config", entityType: "cli_adapter" },
    { action: "activate_cli_adapter_config", entityType: "cli_adapter" },
    { action: "disable_cli_adapter_config", entityType: "cli_adapter" },
  ],
  factSources: ["cli_adapter_configs", "audit_timeline_events"],
} satisfies ConsoleData["settings"];

const overview = {
  summary: {
    totalProjects: 2,
    healthyProjects: 2,
    blockedProjects: 0,
    failedTasks: 0,
    pendingReviews: 3,
    onlineRunners: 2,
    totalCostUsd: 135.96,
  },
  projects: [
    {
      id: "project-1",
      name: "Acme Returns Portal",
      health: "ready",
      repository: "git@github.com:acme/returns-portal.git",
      projectDirectory: "workspace/acme-returns-portal",
      defaultBranch: "main",
      activeFeature: { id: "FEAT-204", title: "Mobile Returns Portal", status: "in-progress" },
      taskCounts: { ready: 4, running: 2, blocked: 2, failed: 0, done: 11 },
      failedTasks: 0,
      pendingReviews: 2,
      activeRuns: 3,
      runnerSuccessRate: 0.957,
      costUsd: 84.32,
      latestRisk: { level: "medium", message: "Refund approval copy needs sign-off", source: "REV-318" },
      lastActivityAt: "2026-04-29T03:45:00.000Z",
    },
    {
      id: "project-2",
      name: "Northwind Supply Planner",
      health: "ready",
      repository: "git@github.com:northwind/supply-planner.git",
      projectDirectory: "workspace/northwind-supply-planner",
      defaultBranch: "develop",
      activeFeature: { id: "FEAT-311", title: "Demand Forecast Review", status: "in-progress" },
      taskCounts: { ready: 2, running: 1, blocked: 1, failed: 0, done: 7 },
      failedTasks: 0,
      pendingReviews: 1,
      activeRuns: 2,
      runnerSuccessRate: 0.924,
      costUsd: 51.64,
      latestRisk: { level: "medium", message: "Forecast override policy needs approval", source: "REV-402" },
      lastActivityAt: "2026-04-29T02:20:00.000Z",
    },
  ],
  signals: [
    { id: "pending-reviews", title: "pending_reviews", tone: "amber", message: "共有 3 项待审查，跨 2 个项目", updatedAt: "刚刚" },
    { id: "blocked-tasks", title: "blocked_tasks", tone: "red", message: "2 个项目中有 3 个任务被阻塞", updatedAt: "2 分钟前" },
    { id: "runner-health", title: "runner_health", tone: "blue", message: "2/2 个 Runner 在线，成功率 93.9%（7 天）", updatedAt: "5 分钟前" },
  ],
  factSources: ["projects", "features", "task_graph_tasks", "runs", "runner_heartbeats", "review_items", "metric_samples"],
} satisfies ConsoleData["overview"];

const returnsAudit = {
  summary: {
    totalEvents: 1248,
    acceptedCommands: 892,
    blockedCommands: 128,
    stateTransitions: 186,
    activityCount: 204,
    pendingApprovals: 42,
  },
  timeline: [
    { id: "AUD-709-APPROVAL", occurredAt: "2026-04-29T14:32:18.000Z", status: "approval", eventType: "approval_recorded", action: "approve_continue", entityType: "review_item", entityId: "REV-318", reason: "auto-approve policy accepted.", requestedBy: "operator", runId: "RUN-709", jobId: "JOB-709", featureId: "FEAT-204", taskId: "T-230", reviewId: "REV-318", blockedReasons: [] },
    { id: "AUD-709-BLOCKED", occurredAt: "2026-04-29T14:31:47.000Z", status: "blocked", eventType: "console_command_run_board_tasks", action: "console_command_run_board_tasks", entityType: "feature", entityId: "FEAT-204", reason: "Command receipt was blocked.", requestedBy: "operator", runId: "RUN-709", jobId: "JOB-709", featureId: "FEAT-204", taskId: "T-230", evidenceId: "EV-318", blockedReasons: ["依赖服务不可用: board-service timeout"] },
    { id: "AUD-709-REASON", occurredAt: "2026-04-29T14:31:45.000Z", status: "blocked", eventType: "blocked_reason", action: "依赖服务不可用: board-service timeout", entityType: "task", entityId: "T-230", reason: "Dependency gate blocked execution.", requestedBy: "operator", runId: "RUN-709", jobId: "JOB-709", featureId: "FEAT-204", taskId: "T-230", blockedReasons: ["board-service timeout"] },
    { id: "AUD-709-TRANSITION", occurredAt: "2026-04-29T14:31:10.000Z", status: "transition", eventType: "state_transition", action: "TASK-READY -> TASK-RUNNING", entityType: "task", entityId: "T-230", reason: "Move approved task into running.", requestedBy: "operator", runId: "RUN-709", jobId: "JOB-709", featureId: "FEAT-204", taskId: "T-230", blockedReasons: [], payload: { fromStatus: "TASK-READY", toStatus: "TASK-RUNNING" } },
    { id: "AUD-709-EVIDENCE", occurredAt: "2026-04-29T14:29:58.000Z", status: "evidence", eventType: "evidence_recorded", action: "exec_log", entityType: "evidence", entityId: "EV-318", reason: "构建日志已上传", requestedBy: "system", runId: "RUN-709", jobId: "JOB-709", featureId: "FEAT-204", taskId: "T-230", evidenceId: "EV-318", blockedReasons: [] },
  ],
  selectedEvent: {
    id: "AUD-709-BLOCKED",
    occurredAt: "2026-04-29T14:31:47.000Z",
    status: "blocked",
    eventType: "console_command_run_board_tasks",
    action: "console_command_run_board_tasks",
    entityType: "feature",
    entityId: "FEAT-204",
    reason: "Command receipt was blocked.",
    requestedBy: "operator",
    runId: "RUN-709",
    jobId: "JOB-709",
    featureId: "FEAT-204",
    taskId: "T-230",
    evidenceId: "EV-318",
    blockedReasons: ["依赖服务不可用: board-service timeout"],
    previousStatus: "TASK-READY",
    currentStatus: "TASK-RUNNING",
    environment: "prod",
  },
  executionResults: [
    { id: "run-709-exec-log.txt", kind: "日志", summary: "CLI execution log", path: ".autobuild/reports/run-709-exec-log.txt", runId: "RUN-709", createdAt: "2026-04-29T14:31:46.000Z" },
    { id: "run-709-stderr.txt", kind: "日志", summary: "stderr output", path: ".autobuild/reports/run-709-stderr.txt", runId: "RUN-709", createdAt: "2026-04-29T14:31:46.000Z" },
  ],
  approvals: [
    { id: "APP-709-AUTO", reviewItemId: "REV-318", actor: "operator", decision: "accepted", reason: "策略: auto-approve", decidedAt: "2026-04-29T14:32:18.000Z" },
    { id: "APP-709-SYSTEM", reviewItemId: "REV-319", actor: "system", decision: "accepted", reason: "依赖检查通过", decidedAt: "2026-04-29T14:30:02.000Z" },
  ],
  filters: {
    eventTypes: ["approval_recorded", "blocked_reason", "console_command_run_board_tasks", "evidence_recorded", "state_transition"],
    entityTypes: ["evidence", "feature", "review_item", "task"],
    statuses: ["approval", "blocked", "evidence", "transition"],
  },
  factSources: ["audit_timeline_events", "state_transitions", "status_check_results", "approval_records", "scheduler_job_records", "runs"],
} satisfies ConsoleData["audit"];

const returnsPortalData: ConsoleProjectData = {
  overview,
  dashboard: {
    projectHealth: { totalProjects: 2, ready: 2, blocked: 0, failed: 0 },
    activeFeatures: [
      { id: "FEAT-204", title: "Mobile Returns Portal", status: "in-progress", priority: 9 },
      { id: "FEAT-203", title: "Refund Rules Engine", status: "ready", priority: 7 },
    ],
    boardCounts: { ready: 4, scheduled: 3, running: 2, review_needed: 2, done: 11 },
    activeRuns: 3,
    todayAutomaticExecutions: 12,
    failedTasks: [],
    pendingApprovals: 2,
    cost: { totalUsd: 84.32, tokensUsed: 642500 },
    runner: { heartbeats: 58, online: 2, successRate: 0.957, failureRate: 0.043 },
    recentPullRequests: [
      { id: "PR-42", title: "feat(returns): add photo evidence upload flow", url: "https://example.test/pr/42", createdAt: "2026-04-29T02:58:00.000Z" },
      { id: "PR-41", title: "test(returns): cover refund eligibility matrix", url: "https://example.test/pr/41", createdAt: "2026-04-28T22:10:00.000Z" },
    ],
    risks: [
      { level: "medium", message: "Refund approval copy needs product sign-off before launch.", source: "REV-318" },
      { level: "medium", message: "Carrier API sandbox has rate limits during browser smoke.", source: "RUN-710" },
    ],
    performance: { loadMs: 96, refreshMs: 38 },
    factSources: ["projects", "features", "task_graph_tasks", "runs", "review_items", "metric_samples"],
  },
  board: {
    tasks: [
      {
        id: "T-226",
        featureId: "FEAT-204",
        title: "Draft return request intake spec",
        status: "done",
        risk: "low",
        dependencies: [],
        diff: { files: ["docs/features/feat-204-mobile-returns/requirements.md"], additions: 118, deletions: 4 },
        testResults: { command: "npm test", passed: true, total: 24 },
        approvalStatus: "approved",
        recoveryHistory: [],
        blockedReasons: [],
      },
      {
        id: "T-227",
        featureId: "FEAT-204",
        title: "Implement order lookup and eligibility cards",
        status: "done",
        risk: "medium",
        dependencies: [{ id: "T-226", status: "done", satisfied: true }],
        diff: { files: ["apps/web/src/returns/OrderLookup.tsx", "src/returns.ts"], additions: 264, deletions: 31 },
        testResults: { command: "npm test -- returns", passed: true, total: 31 },
        approvalStatus: "approved",
        recoveryHistory: [],
        blockedReasons: [],
      },
      {
        id: "T-228",
        featureId: "FEAT-204",
        title: "Add photo evidence upload with preview",
        status: "running",
        risk: "medium",
        dependencies: [{ id: "T-227", status: "done", satisfied: true }],
        diff: { files: ["apps/web/src/returns/EvidenceUpload.tsx", "src/evidence-store.ts"], additions: 193, deletions: 16 },
        testResults: { command: "npm run console:build", passed: true, total: 14 },
        approvalStatus: "not_required",
        recoveryHistory: [],
        blockedReasons: [],
      },
      {
        id: "T-229",
        featureId: "FEAT-204",
        title: "Connect carrier label quote mock",
        status: "scheduled",
        risk: "medium",
        dependencies: [{ id: "T-228", status: "running", satisfied: false }],
        diff: { files: ["src/carrier-labels.ts", "tests/carrier-labels.test.ts"], additions: 146, deletions: 11 },
        testResults: { command: "node --test tests/carrier-labels.test.ts", passed: true, total: 12 },
        approvalStatus: "pending",
        recoveryHistory: [{ from: "blocked", to: "scheduled", reason: "Carrier sandbox replaced by deterministic local fixture.", occurredAt: "2026-04-29T02:40:00.000Z" }],
        blockedReasons: ["Waiting for T-228 upload contract to be finalized."],
      },
      {
        id: "T-230",
        featureId: "FEAT-204",
        title: "Review refund approval copy",
        status: "review_needed",
        risk: "medium",
        dependencies: [{ id: "T-227", status: "done", satisfied: true }],
        diff: { files: ["apps/web/src/returns/RefundDecision.tsx", "docs/features/feat-204-mobile-returns/copy.md"], additions: 74, deletions: 22 },
        testResults: { command: "npm test -- refund-copy", passed: true, total: 9 },
        approvalStatus: "pending",
        recoveryHistory: [],
        blockedReasons: ["Product approval is required for customer-facing refund decision copy."],
      },
      {
        id: "T-231",
        featureId: "FEAT-204",
        title: "Run mobile browser acceptance",
        status: "ready",
        risk: "low",
        dependencies: [
          { id: "T-228", status: "running", satisfied: false },
          { id: "T-230", status: "review_needed", satisfied: false },
        ],
        diff: { files: ["apps/web/src/test/returns-mobile.spec.ts"], additions: 102, deletions: 0 },
        testResults: { command: "npm run console:test", passed: true, total: 7 },
        approvalStatus: "not_required",
        recoveryHistory: [],
        blockedReasons: ["Waiting for upload and copy review tasks before final acceptance."],
      },
    ],
    commands: [
      { action: "move_board_task", entityType: "task" },
      { action: "schedule_board_tasks", entityType: "feature" },
      { action: "run_board_tasks", entityType: "feature" },
    ],
    factSources: ["task_graph_tasks", "review_items", "approval_records", "status_check_results", "state_transitions"],
  },
  spec: {
    prdWorkflow: {
      targetRepoPath: "workspace/acme-returns-portal",
      sourcePath: "docs/zh-CN/PRD.md",
      resolvedSourcePath: "workspace/acme-returns-portal/docs/zh-CN/PRD.md",
      sourceVersion: "v1.3.0",
      scanMode: "smart",
      lastScanAt: "05-19 09:12",
      runtime: "10m 24s",
      blockedReasons: ["存在阻塞项，无法进入调度状态"],
      phases: [
        {
          key: "project_initialization",
          status: "completed",
          updatedAt: "05-19 09:10",
          blockedReasons: [],
          facts: [
            { label: "Project", value: "Acme Returns Portal" },
            { label: "Repository", value: "workspace/acme-returns-portal" },
            { label: "Health", value: "ready" },
          ],
          stages: [
            { key: "create_or_import_project", status: "completed", updatedAt: "05-19 09:04" },
            { key: "connect_git_repository", status: "completed", updatedAt: "05-19 09:05" },
            { key: "initialize_spec_protocol", status: "completed", updatedAt: "05-19 09:07" },
            { key: "import_or_create_constitution", status: "completed", updatedAt: "05-19 09:08" },
            { key: "initialize_project_memory", status: "completed", updatedAt: "05-19 09:10" },
          ],
        },
        {
          key: "requirement_intake",
          status: "blocked",
          updatedAt: "05-19 09:16",
          blockedReasons: ["存在阻塞项，无法进入调度状态"],
          facts: [
            { label: "PRD", value: "workspace/acme-returns-portal/docs/zh-CN/PRD.md" },
            { label: "Features", value: "3" },
            { label: "Requirements", value: "3" },
          ],
          stages: [
            { key: "spec_source_intake", status: "completed", updatedAt: "05-19 09:14" },
            { key: "recognize_requirement_format", status: "completed", updatedAt: "05-19 09:15" },
            { key: "generate_ears", action: "generate_ears", status: "completed", updatedAt: "05-19 09:16", auditEventId: "AUD-PRD-003", resultPath: "ears/FEAT-013.md" },
            { key: "complete_clarifications", status: "completed", updatedAt: "05-19 09:17" },
            { key: "run_requirement_quality_check", status: "completed", updatedAt: "05-19 09:18" },
          ],
        },
        {
          key: "feature_execution",
          status: "pending",
          updatedAt: "05-19 09:21",
          blockedReasons: [],
          facts: [
            { label: "Feature", value: "FEAT-204" },
            { label: "Status", value: "implementing" },
            { label: "Command", value: "schedule_run" },
            { label: "UI outputs", value: "docs/ui/ui-spec.md + docs/ui/concepts/*.png" },
          ],
          stages: [
            { key: "generate_hld", action: "generate_hld", status: "pending" },
            { key: "generate_ui_spec", action: "generate_ui_spec", status: "pending" },
            { key: "split_feature_specs", action: "split_feature_specs", status: "pending" },
            { key: "task_scheduling", action: "start_auto_run", status: "pending" },
            { key: "status_check", action: "schedule_run", status: "pending" },
          ],
        },
      ],
      stages: [
        { key: "scan_prd", action: "scan_prd_source", status: "completed", updatedAt: "05-19 09:12", auditEventId: "AUD-PRD-001", resultPath: "reports/FEAT-013-scan.md" },
        { key: "upload_prd", action: "upload_prd_source", status: "completed", updatedAt: "05-19 09:14", auditEventId: "AUD-PRD-002", resultPath: "reports/FEAT-013-upload.md" },
        { key: "generate_ears", action: "generate_ears", status: "completed", updatedAt: "05-19 09:16", auditEventId: "AUD-PRD-003", resultPath: "ears/FEAT-013.md" },
      ],
      specSources: [
        { type: "prd", label: "PRD", path: "workspace/acme-returns-portal/docs/zh-CN/PRD.md", status: "found" },
        { type: "ears", label: "EARS", path: "workspace/acme-returns-portal/docs/zh-CN/requirements.md", status: "found" },
        { type: "requirements", label: "Requirements", path: "workspace/acme-returns-portal/docs/en/requirements.md", status: "found" },
        { type: "hld", label: "HLD", path: "workspace/acme-returns-portal/docs/zh-CN/hld.md", status: "found" },
        { type: "design", label: "Design", status: "missing", detail: "No design.md found in docs/" },
        { type: "feature_spec", label: "Feature Spec", path: "workspace/acme-returns-portal/docs/features/", status: "found", detail: "3 feature specs" },
        { type: "tasks", label: "Tasks", path: "workspace/acme-returns-portal/docs/features/", status: "found", detail: "3 tasks.md files" },
        { type: "readme", label: "README / Index", path: "workspace/acme-returns-portal/docs/features/README.md", status: "conflict", detail: "Feature index references FEAT-204 but folder is missing" },
      ],
    },
    features: [
      { id: "FEAT-204", title: "Mobile Returns Portal", folder: "feat-204-mobile-returns", status: "implementing", primaryRequirements: ["REQ-204-001", "REQ-204-002", "REQ-204-003"] },
      { id: "FEAT-203", title: "Refund Rules Engine", folder: "feat-203-refund-rules", status: "ready", primaryRequirements: ["REQ-203-001", "REQ-203-004"] },
      { id: "FEAT-202", title: "Customer Notification Timeline", folder: "feat-202-notification-timeline", status: "done", primaryRequirements: ["REQ-202-001"] },
    ],
    selectedFeature: {
      id: "FEAT-204",
      title: "Mobile Returns Portal",
      requirements: [
        { id: "REQ-204-001", body: "Customers can find eligible orders by email and order number.", priority: "MVP" },
        { id: "REQ-204-002", body: "Customers can attach photo evidence and preview files before submission.", priority: "MVP" },
        { id: "REQ-204-003", body: "The portal shows refund decision copy and carrier label options before confirmation.", priority: "MVP" },
        { id: "EDGE-204-001", body: "Expired, final-sale, and already-returned orders must show a non-submittable decision.", priority: "MVP" },
      ],
      documents: {
        requirements: {
          path: "docs/features/feat-204-mobile-returns/requirements.md",
          exists: true,
          title: "Feature Spec: FEAT-204 Mobile Returns Portal",
          sections: [
            { heading: "Requirements", level: 2, body: "- REQ-204-001 Customers can find eligible orders.\n- REQ-204-003 The portal shows carrier label options." },
            { heading: "Acceptance Criteria", level: 2, body: "- Customer can complete the mobile return flow.\n- Expired orders are blocked with a clear reason." },
          ],
          raw: "# Feature Spec: FEAT-204 Mobile Returns Portal\n\nSpec Evolution:\n- CHG-204-003 Added local carrier label fixture.\n\n## Requirements\n- REQ-204-001 Customers can find eligible orders.\n- REQ-204-003 The portal shows carrier label options.\n\n## Acceptance Criteria\n- Customer can complete the mobile return flow.\n- Expired orders are blocked with a clear reason.",
        },
        design: {
          path: "docs/features/feat-204-mobile-returns/design.md",
          exists: true,
          title: "Design: FEAT-204 Mobile Returns Portal",
          sections: [
            { heading: "Design Summary", level: 2, body: "Mobile returns are implemented as a guided customer workflow with mocked carrier labels." },
            { heading: "Controlled Command Boundary", level: 2, body: "Return submission writes through governed API commands and records evidence." },
            { heading: "Review and Evidence", level: 2, body: "Browser evidence covers mobile layout and carrier quote rendering." },
          ],
          raw: "# Design: FEAT-204 Mobile Returns Portal\n\n## Design Summary\nMobile returns are implemented as a guided customer workflow with mocked carrier labels.\n\n## Controlled Command Boundary\nReturn submission writes through governed API commands and records evidence.\n\n## Review and Evidence\nBrowser evidence covers mobile layout and carrier quote rendering.",
        },
        tasks: {
          path: "docs/features/feat-204-mobile-returns/tasks.md",
          exists: true,
          sections: [{ heading: "Tasks", level: 2, body: "- [x] Connect carrier label quote mock." }],
        },
      },
      clarificationRecords: [
        { id: "CLR-204-001", summary: "Product chose customer-facing return reasons over internal RMA codes." },
        { id: "CLR-204-002", summary: "Carrier quote integration remains mocked for launch demo." },
      ],
      qualityChecklist: [
        { item: "requirements_present", passed: true },
        { item: "mobile_acceptance_path_defined", passed: true },
        { item: "copy_review_pending", passed: false },
      ],
      dataModels: [
        { entities: ["ReturnRequest", "ReturnEvidence", "RefundDecision", "CarrierLabelQuote"] },
      ],
      contracts: [
        { endpoints: ["/returns/orders/lookup", "/returns/evidence", "/returns/label-quotes"] },
        { events: ["return_request.submitted", "refund_decision.reviewed"] },
      ],
      versionDiffs: [
        { id: "CHG-204-003", summary: "Added local carrier label fixture and mobile screenshot acceptance." },
      ],
      skillOutput: {
        parseStatus: "found",
        stdoutLogPath: "workspace/acme-returns-portal/.autobuild/runs/RUN-709/stdout.log",
        status: "completed",
        summary: "Carrier label quote fixture wired and acceptance evidence recorded.",
        tokenUsage: { inputTokens: 18420, outputTokens: 2310, totalTokens: 20730 },
        inputContract: {
          skillName: "implement-feature",
          skillPhase: "task_execution",
          required: ["featureId", "featureSpecPath", "workspaceRoot"],
          context: { featureId: "FEAT-204", featureSpecPath: "docs/features/feat-204-mobile-returns", workspaceRoot: "workspace/acme-returns-portal" },
        },
        producedArtifacts: [{ path: "docs/features/feat-204-mobile-returns/tasks.md", kind: "markdown", status: "updated" }],
        evidence: [{ kind: "browser", summary: "Mobile return quote flow rendered.", path: ".autobuild/reports/RUN-709.json" }],
        traceability: { featureId: "FEAT-204", requirementIds: ["REQ-204-003"], changeIds: ["CHG-204-003"] },
        result: { completedTasks: ["T-229"] },
        raw: {
          contractVersion: "skill-contract/v1",
          executionId: "RUN-709",
          status: "completed",
          summary: "Carrier label quote fixture wired and acceptance evidence recorded.",
        },
      },
    },
  },
  runner: {
    summary: { onlineRunners: 1, runningTasks: 1, readyTasks: 1, blockedTasks: 2, successRate: 0.957, failureRate: 0.043 },
    schedulerJobs: [
      { id: "JOB-709", bullmqJobId: "BULL-709", queueName: "specdrive:cli-runner", jobType: "cli.run", operation: "feature_execution", targetType: "execution", targetId: "RUN-709", status: "queued", attempts: 0, updatedAt: "2026-04-29T03:42:00.000Z", executionId: "RUN-709", runId: "RUN-709", taskId: "T-229", featureId: "FEAT-204", projectId: "project-1", workspaceRoot: "workspace/acme-returns-portal", context: { featureId: "FEAT-204", featureSpecPath: "docs/features/FEAT-204/tasks.md", taskId: "T-229", taskName: "Connect carrier label quote mock", workspaceRoot: "workspace/acme-returns-portal", skillName: "implement-feature", skillPhase: "task_execution" }, skillOutput: {
        parseStatus: "found",
        stdoutLogPath: "workspace/acme-returns-portal/.autobuild/runs/RUN-709/stdout.log",
        status: "completed",
        summary: "Carrier label quote fixture wired and acceptance evidence recorded.",
        tokenUsage: { inputTokens: 18420, outputTokens: 2310, totalTokens: 20730 },
        inputContract: {
          skillName: "implement-feature",
          skillPhase: "task_execution",
          required: ["featureId", "featureSpecPath", "workspaceRoot"],
          context: { featureId: "FEAT-204", featureSpecPath: "docs/features/feat-204-mobile-returns", workspaceRoot: "workspace/acme-returns-portal" },
        },
        producedArtifacts: [{ path: "docs/features/feat-204-mobile-returns/tasks.md", kind: "markdown", status: "updated" }],
        evidence: [{ kind: "browser", summary: "Mobile return quote flow rendered.", path: ".autobuild/reports/RUN-709.json" }],
        traceability: { featureId: "FEAT-204", requirementIds: ["REQ-204-003"], changeIds: ["CHG-204-003"] },
        result: { completedTasks: ["T-229"] },
        raw: { contractVersion: "skill-contract/v1", executionId: "RUN-709", status: "completed", summary: "Carrier label quote fixture wired and acceptance evidence recorded." },
      } },
      { id: "JOB-711", bullmqJobId: "BULL-711", queueName: "specdrive:cli-runner", jobType: "cli.run", operation: "generate_hld", targetType: "execution", targetId: "RUN-711", status: "blocked", attempts: 1, error: "Project workspace is missing readable AGENTS.md", updatedAt: "2026-04-29T03:41:30.000Z", executionId: "RUN-711", runId: "RUN-711", projectId: "project-1", workspaceRoot: "workspace/acme-returns-portal", context: { workspaceRoot: "workspace/acme-returns-portal", skillName: "design-architecture", skillPhase: "feature_execution" } },
      ...Array.from({ length: 11 }, (_, index) => ({
        id: `JOB-PAGE-${index}`,
        bullmqJobId: `BULL-PAGE-${index}`,
        queueName: "specdrive:cli-runner",
        jobType: "cli.run",
        operation: "feature_execution",
        targetType: "execution",
        targetId: `RUN-PAGE-${index}`,
        status: index % 2 === 0 ? "queued" : "completed",
        attempts: 0,
        updatedAt: `2026-04-29T03:${String(20 + index).padStart(2, "0")}:00.000Z`,
        executionId: `RUN-PAGE-${index}`,
        runId: `RUN-PAGE-${index}`,
        taskId: `T-PAGE-${index}`,
        featureId: "FEAT-204",
        projectId: "project-1",
        workspaceRoot: "workspace/acme-returns-portal",
        context: { taskName: `Paginated task ${index}`, skillName: "implement-feature", skillPhase: "task_execution" },
      })),
    ],
    lanes: {
      ready: [
        { id: "T-231", featureId: "FEAT-204", featureTitle: "Mobile Returns Portal", title: "Run mobile browser acceptance", status: "ready", risk: "low", dependencies: [{ id: "T-228", status: "running", satisfied: false }, { id: "T-230", status: "review_needed", satisfied: false }], approvalStatus: "not_required", action: "schedule", blockedReasons: [], recentLog: "npm run console:test -- returns-mobile" },
      ],
      scheduled: [
        { id: "T-229", featureId: "FEAT-204", featureTitle: "Mobile Returns Portal", title: "Connect carrier label quote mock", description: "Queue the carrier label quote implementation against the local fixture contract and browser acceptance evidence.", status: "scheduled", risk: "medium", sourceRequirementIds: ["REQ-204"], acceptanceCriteriaIds: ["AC-204-CARRIER-LABEL"], allowedFiles: ["src/carrier-labels.ts", "tests/carrier-labels.test.ts"], dependencies: [{ id: "T-228", status: "running", satisfied: false }], approvalStatus: "pending", runnerId: "runner-web-01", runId: "RUN-709", action: "run", blockedReasons: ["Waiting for T-228 upload contract to be finalized."], resultSummary: "Carrier label fixture decision recorded in contracts.", recentLog: "node --test tests/carrier-labels.test.ts" },
      ],
      running: [
        { id: "T-228", featureId: "FEAT-204", featureTitle: "Mobile Returns Portal", title: "Add photo evidence upload with preview", status: "running", risk: "medium", dependencies: [{ id: "T-227", status: "done", satisfied: true }], approvalStatus: "not_required", runnerId: "runner-web-01", runId: "RUN-708", action: "observe", blockedReasons: [], recentLog: "Mobile upload preview rendered and evidence fixture stored." },
      ],
      blocked: [
        { id: "T-230", featureId: "FEAT-204", featureTitle: "Mobile Returns Portal", title: "Review refund approval copy", status: "review_needed", risk: "medium", dependencies: [{ id: "T-227", status: "done", satisfied: true }], approvalStatus: "pending", action: "review", blockedReasons: ["Product approval is required for customer-facing refund decision copy."], recentLog: "REV-318 waiting on product sign-off." },
        { id: "T-232", featureId: "FEAT-204", featureTitle: "Mobile Returns Portal", title: "Publish governed return demo", status: "blocked", risk: "high", dependencies: [{ id: "T-230", status: "review_needed", satisfied: false }], approvalStatus: "pending", action: "review", blockedReasons: ["High risk release task requires approval before Runner execution."], recentLog: "Release gate held by Review Center." },
      ],
    },
    recentTriggers: [
      { id: "TRG-204-003", action: "manual", target: "feature:FEAT-204", result: "accepted", createdAt: "2026-04-29T03:42:00.000Z" },
      { id: "AUD-204-011", action: "schedule_board_tasks", target: "feature:FEAT-204", result: "blocked", createdAt: "2026-04-29T03:38:00.000Z" },
      { id: "AUD-204-010", action: "run_board_tasks", target: "feature:FEAT-204", result: "accepted", createdAt: "2026-04-29T03:12:00.000Z" },
    ],
    skillInvocations: [
      {
        runId: "RUN-709",
        schedulerJobId: "JOB-709",
        workspaceRoot: "workspace/acme-returns-portal",
        skillName: "implement-feature",
        skillPhase: "task_execution",
        status: "queued",
        resultSummary: "Codex skill invocation contract queued for workspace execution.",
        output: {
          parseStatus: "found",
          stdoutLogPath: "workspace/acme-returns-portal/.autobuild/runs/RUN-709/stdout.log",
          status: "completed",
          summary: "Carrier label quote fixture wired and acceptance evidence recorded.",
          tokenUsage: { inputTokens: 18420, outputTokens: 2310, totalTokens: 20730 },
          inputContract: {
            skillName: "implement-feature",
            skillPhase: "task_execution",
            required: ["featureId", "featureSpecPath", "workspaceRoot"],
            context: { featureId: "FEAT-204", featureSpecPath: "docs/features/feat-204-mobile-returns", workspaceRoot: "workspace/acme-returns-portal" },
          },
          producedArtifacts: [{ path: "docs/features/feat-204-mobile-returns/tasks.md", kind: "markdown", status: "updated" }],
          evidence: [{ kind: "browser", summary: "Mobile return quote flow rendered.", path: ".autobuild/reports/RUN-709.json" }],
          traceability: { featureId: "FEAT-204", requirementIds: ["REQ-204-003"], changeIds: ["CHG-204-003"] },
          result: { completedTasks: ["T-229"] },
          raw: { contractVersion: "skill-contract/v1", executionId: "RUN-709", status: "completed", summary: "Carrier label quote fixture wired and acceptance evidence recorded." },
        },
        updatedAt: "2026-04-29T03:42:00.000Z",
      },
      {
        runId: "RUN-710",
        schedulerJobId: "JOB-710",
        workspaceRoot: "workspace/acme-returns-portal",
        skillName: "collect-project-context",
        skillPhase: "feature_execution",
        blockedReason: "Project workspace is missing readable AGENTS.md",
        status: "blocked",
        updatedAt: "2026-04-29T03:41:00.000Z",
      },
    ],
    factSources: ["task_graph_tasks", "runs", "runner_heartbeats", "runner_policies", "scheduler_job_records", "raw_execution_logs", "review_items", "audit_timeline_events"],
    adapterSummary: {
      id: cliAdapterConfig.id,
      displayName: cliAdapterConfig.displayName,
      status: cliAdapterConfig.status,
      schemaVersion: cliAdapterConfig.schemaVersion,
      executable: cliAdapterConfig.executable,
      lastDryRunStatus: "passed",
      lastDryRunAt: "2026-04-29T03:45:00.000Z",
      lastDryRunErrors: [],
      settingsPath: "/settings/cli",
    },
    runners: [
      { runnerId: "runner-web-01", online: true, runnerModel: "gpt-5.4", sandboxMode: "workspace-write", approvalPolicy: "never", queue: [{ runId: "RUN-708", status: "running" }, { runId: "RUN-709", status: "queued" }, { runId: "RUN-710", status: "queued" }], recentLogs: [{ runId: "RUN-708", stdout: "Mobile upload preview rendered and evidence fixture stored.", stderr: "", createdAt: "2026-04-29T03:40:00.000Z" }], lastHeartbeatAt: "2026-04-29T03:45:00.000Z", heartbeatStale: false },
    ],
  },
  settings,
  reviews: {
    riskFilters: ["high", "medium"],
    items: [
      { id: "REV-318", featureId: "FEAT-204", taskId: "T-230", status: "review_needed", severity: "medium", body: "Refund decision copy needs product approval before customer demo.", evidence: [{ id: "EV-318", summary: "Copy diff and screenshot are attached.", path: ".autobuild/reports/REV-318.json" }], approvals: [], createdAt: "2026-04-29T03:15:00.000Z" },
      { id: "REV-319", featureId: "FEAT-204", taskId: "T-229", status: "review_needed", severity: "medium", body: "Carrier label fixture replaces external sandbox for demo stability.", evidence: [{ id: "EV-319", summary: "Fixture decision recorded in contracts.", path: ".autobuild/reports/REV-319.json" }], approvals: [], createdAt: "2026-04-29T03:28:00.000Z" },
    ],
  },
  audit: returnsAudit,
};

const supplyPlannerData: ConsoleProjectData = {
  ...returnsPortalData,
  dashboard: {
    ...returnsPortalData.dashboard,
    activeFeatures: [{ id: "FEAT-311", title: "Demand Forecast Review", status: "in-progress", priority: 8 }],
    pendingApprovals: 1,
    activeRuns: 2,
    cost: { totalUsd: 51.64, tokensUsed: 418900 },
    risks: [{ level: "medium", message: "Forecast override policy needs operations approval.", source: "REV-402" }],
  },
  board: {
    ...returnsPortalData.board,
    tasks: [
      {
        ...returnsPortalData.board.tasks[0],
        id: "T-401",
        featureId: "FEAT-311",
        title: "Model forecast confidence bands",
      },
      {
        ...returnsPortalData.board.tasks[2],
        id: "T-402",
        featureId: "FEAT-311",
        title: "Build planner override table",
      },
      {
        ...returnsPortalData.board.tasks[4],
        id: "T-403",
        featureId: "FEAT-311",
        title: "Review override approval copy",
        blockedReasons: ["Operations approval is required for override copy."],
      },
    ],
  },
  spec: {
    features: [
      { id: "FEAT-311", title: "Demand Forecast Review", folder: "feat-311-demand-forecast-review", status: "implementing", primaryRequirements: ["REQ-311-001", "REQ-311-002"] },
      { id: "FEAT-310", title: "Inventory Signal Intake", folder: "feat-310-inventory-signal-intake", status: "ready", primaryRequirements: ["REQ-310-001", "REQ-310-002"] },
      { id: "FEAT-309", title: "Planner Approval Workflow", folder: "feat-309-planner-approval-workflow", status: "done", primaryRequirements: ["REQ-309-001"] },
    ],
    selectedFeature: {
      ...returnsPortalData.spec.selectedFeature!,
      id: "FEAT-311",
      title: "Demand Forecast Review",
      requirements: [
        { id: "REQ-311-001", body: "Planners can review confidence bands by SKU and warehouse.", priority: "MVP" },
        { id: "REQ-311-002", body: "Planners can submit governed forecast overrides with approval evidence.", priority: "MVP" },
      ],
    },
  },
  reviews: {
    riskFilters: ["medium"],
    items: [
      { id: "REV-402", featureId: "FEAT-311", taskId: "T-403", status: "review_needed", severity: "medium", body: "Forecast override policy needs operations approval.", evidence: [{ id: "EV-402", summary: "Override policy diff attached.", path: ".autobuild/reports/REV-402.json" }], approvals: [], createdAt: "2026-04-29T02:18:00.000Z" },
    ],
  },
  audit: {
    ...returnsAudit,
    summary: { ...returnsAudit.summary, totalEvents: 418, acceptedCommands: 301, blockedCommands: 37, pendingApprovals: 9 },
    timeline: returnsAudit.timeline.map((event) => ({ ...event, featureId: "FEAT-311", taskId: "T-403", entityId: event.entityType === "feature" ? "FEAT-311" : event.entityId })),
  },
};

const emptyProjectData: ConsoleProjectData = {
  overview,
  dashboard: { ...returnsPortalData.dashboard, activeFeatures: [], failedTasks: [], pendingApprovals: 0, activeRuns: 0, risks: [], recentPullRequests: [], boardCounts: {} },
  board: { tasks: [], commands: returnsPortalData.board.commands, factSources: returnsPortalData.board.factSources },
  spec: { features: [], selectedFeature: undefined },
  runner: { summary: { onlineRunners: 0, runningTasks: 0, readyTasks: 0, blockedTasks: 0, successRate: 0, failureRate: 0 }, schedulerJobs: [], lanes: { ready: [], scheduled: [], running: [], blocked: [] }, recentTriggers: [], factSources: [], adapterSummary: returnsPortalData.runner.adapterSummary, runners: [] },
  settings,
  reviews: { items: [], riskFilters: [] },
  audit: { summary: { totalEvents: 0, acceptedCommands: 0, blockedCommands: 0, stateTransitions: 0, activityCount: 0, pendingApprovals: 0 }, timeline: [], executionResults: [], approvals: [], filters: { eventTypes: [], entityTypes: [], statuses: [] }, factSources: [] },
};

const projectData: Record<string, ConsoleProjectData> = {
  "project-1": returnsPortalData,
  "project-2": supplyPlannerData,
};

export const demoData: ConsoleData = {
  projects,
  ...returnsPortalData,
};

export const emptyData: ConsoleData = {
  projects,
  ...emptyProjectData,
};

export function getDemoDataForProject(projectId: string): ConsoleProjectData {
  return projectData[projectId] ?? emptyProjectData;
}
